SET DEFINE OFF

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEKR, TYPEALIAS) 
VALUES (1.0, '경리', 'AC');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEKR, TYPEALIAS) 
VALUES (2.0, '고객관리', 'CS');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEKR, TYPEALIAS) 
VALUES (3.0, '총무', 'GA');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEKR, TYPEALIAS) 
VALUES (4.0, '인사', 'HR');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEKR, TYPEALIAS) 
VALUES (5.0, '유통', 'LT');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEKR, TYPEALIAS) 
VALUES (6.0, '보수', 'MA');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEKR, TYPEALIAS) 
VALUES (7.0, '경영지원', 'MA');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEKR, TYPEALIAS) 
VALUES (8.0, '경영개선', 'MI');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEKR, TYPEALIAS) 
VALUES (9.0, '자재', 'MT');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEKR, TYPEALIAS) 
VALUES (10.0, '생산', 'PD');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEKR, TYPEALIAS) 
VALUES (11.0, '홍보', 'PR');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEKR, TYPEALIAS) 
VALUES (12.0, '구매', 'PC');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEKR, TYPEALIAS) 
VALUES (13.0, '품질관리', 'QC');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEKR, TYPEALIAS) 
VALUES (14.0, '영업', 'S');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEKR, TYPEALIAS) 
VALUES (15.0, '기술', 'TECH');