SET DEFINE OFF

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEEN, DEPNAMEKR, TYPEALIAS) 
VALUES (1.0, 'Accounting', '경리', 'AC');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEEN, DEPNAMEKR, TYPEALIAS) 
VALUES (2.0, 'CustomerService', '고객관리', 'CS');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEEN, DEPNAMEKR, TYPEALIAS) 
VALUES (3.0, 'General Affairs', '총무', 'GA');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEEN, DEPNAMEKR, TYPEALIAS) 
VALUES (4.0, 'Human Resources', '인사', 'HR');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEEN, DEPNAMEKR, TYPEALIAS) 
VALUES (5.0, 'Logistics', '유통', 'LT');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEEN, DEPNAMEKR, TYPEALIAS) 
VALUES (6.0, 'Maintenance', '보수', 'MA');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEEN, DEPNAMEKR, TYPEALIAS) 
VALUES (7.0, 'Management Assistant', '경영지원', 'MA');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEEN, DEPNAMEKR, TYPEALIAS) 
VALUES (8.0, 'Management Improving', '경영개선', 'MI');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEEN, DEPNAMEKR, TYPEALIAS) 
VALUES (9.0, 'Materials', '자재', 'MT');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEEN, DEPNAMEKR, TYPEALIAS) 
VALUES (10.0, 'Production', '생산', 'PD');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEEN, DEPNAMEKR, TYPEALIAS) 
VALUES (11.0, 'Public Relations', '홍보', 'PR');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEEN, DEPNAMEKR, TYPEALIAS) 
VALUES (12.0, 'Purchasing', '구매', 'PC');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEEN, DEPNAMEKR, TYPEALIAS) 
VALUES (13.0, 'Quality Control', '품질관리', 'QC');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEEN, DEPNAMEKR, TYPEALIAS) 
VALUES (14.0, 'Sales', '영업', 'S');

INSERT INTO CP_DEPARTMENT (DEPNUM, DEPNAMEEN, DEPNAMEKR, TYPEALIAS) 
VALUES (15.0, 'Technical', '기술', 'TECH');
