SET DEFINE OFF

INSERT INTO CP_POSITION (POSITIONNUM, POSITIONNAME) 
VALUES (1.0, '전무');

INSERT INTO CP_POSITION (POSITIONNUM, POSITIONNAME) 
VALUES (2.0, '상무');

INSERT INTO CP_POSITION (POSITIONNUM, POSITIONNAME) 
VALUES (3.0, '이사');

INSERT INTO CP_POSITION (POSITIONNUM, POSITIONNAME) 
VALUES (4.0, '부장');

INSERT INTO CP_POSITION (POSITIONNUM, POSITIONNAME) 
VALUES (5.0, '차장');

INSERT INTO CP_POSITION (POSITIONNUM, POSITIONNAME) 
VALUES (6.0, '과장');

INSERT INTO CP_POSITION (POSITIONNUM, POSITIONNAME) 
VALUES (7.0, '대리');

INSERT INTO CP_POSITION (POSITIONNUM, POSITIONNAME) 
VALUES (8.0, '주임');

INSERT INTO CP_POSITION (POSITIONNUM, POSITIONNAME) 
VALUES (9.0, '사원');

INSERT INTO CP_POSITION (POSITIONNUM, POSITIONNAME) 
VALUES (10.0, '인턴');